name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test thoi
        run: |
          echo "DB_USER=${{ vars.DB_USER }}"
          echo "DB_PASS=${{ secrets.DB_PASS }}"