name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test thoi
        run: |
          echo "DB_USER=${{ vars.DB_USER }}"
      - name: Extra secrets.DB_PASS
        run: |
          echo "DB_USER=${{ vars.DB_USER }}"
          echo "$DB_PASS_env"
        shell: bash
        env:
          DB_PASS_env: ${{secrets.DB_PASS}}